/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projek_kelmp5;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kelas.Data_Pengajar;
import java.sql.SQLException;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
/**
 *
 * @author HP
 */
public class UstadzPanel extends javax.swing.JPanel {

    /**
     * Creates new form UstadzPanel
     */
    public UstadzPanel() {
        initComponents();
        
        load_table();
        tblUstadz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUstadzMouseClicked(evt);
            }
        });        
    }
    
    void reset() {
        tidPengajar.setText("");
        tidPengajar.setText("");
        tnamaLengkap.setText("");
        tnoHP.setText("");
        
        buttonGroup1.clearSelection();
    }
    public void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Nama Lengkap");
        model.addColumn("Alamat");
        model.addColumn("No. HP");
        model.addColumn("Jenis Kelamin");
        
        ResultSet result = null;
        try {
            Data_Pengajar pgr = new Data_Pengajar();
            result = pgr.tampilUstadz();
            
            while (result.next()){
                model.addRow(new Object[]{
                    result.getInt("id_ustadz"),
                    result.getString("nama_ustadz"),
                    result.getString("alamat"),
                    result.getString("no_hp"),
                    result.getString("jenis_kelamin")
                });
            }
            
            tblUstadz.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat data tabel. Eror : " 
                    + e.getMessage());
        } finally {
            try {
                if (result != null){
                    result.close();
                }
            } catch (Exception e) {
                System.out.println("Error saat menutup ResultSet: "
                        + e.getMessage());
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        MainPanelPengurus = new javax.swing.JPanel();
        DataPengajar = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        tnoHP = new javax.swing.JTextField();
        talamat = new javax.swing.JTextField();
        tidPengajar = new javax.swing.JTextField();
        tnamaLengkap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        radioButtonLK1 = new javax.swing.JRadioButton();
        radioButtonPR = new javax.swing.JRadioButton();
        buttonHapus = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUstadz = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        MainPanelPengurus.setLayout(new java.awt.CardLayout());

        DataPengajar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setActionCommand("<Not Set>");
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        DataPengajar.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 300, 20));

        tnoHP.setBackground(new java.awt.Color(255, 255, 255));
        tnoHP.setForeground(new java.awt.Color(0, 0, 0));
        tnoHP.setBorder(null);
        tnoHP.setCaretColor(new java.awt.Color(0, 0, 0));
        DataPengajar.add(tnoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 270, 20));

        talamat.setBackground(new java.awt.Color(255, 255, 255));
        talamat.setForeground(new java.awt.Color(0, 0, 0));
        talamat.setBorder(null);
        talamat.setCaretColor(new java.awt.Color(0, 0, 0));
        DataPengajar.add(talamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 270, 20));

        tidPengajar.setBackground(new java.awt.Color(255, 255, 255));
        tidPengajar.setForeground(new java.awt.Color(0, 0, 0));
        tidPengajar.setBorder(null);
        tidPengajar.setCaretColor(new java.awt.Color(0, 0, 0));
        tidPengajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidPengajarActionPerformed(evt);
            }
        });
        DataPengajar.add(tidPengajar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 270, 20));

        tnamaLengkap.setBackground(new java.awt.Color(255, 255, 255));
        tnamaLengkap.setForeground(new java.awt.Color(0, 0, 0));
        tnamaLengkap.setBorder(null);
        tnamaLengkap.setCaretColor(new java.awt.Color(0, 0, 0));
        tnamaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaLengkapActionPerformed(evt);
            }
        });
        DataPengajar.add(tnamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 270, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Jenis Kelamin");
        jLabel2.setPreferredSize(new java.awt.Dimension(40, 20));
        DataPengajar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 270, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Data Pengajar");
        jLabel4.setPreferredSize(new java.awt.Dimension(40, 20));
        DataPengajar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 420, 60));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID Pengajar");
        jLabel5.setPreferredSize(new java.awt.Dimension(40, 20));
        DataPengajar.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 270, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Alamat");
        jLabel6.setPreferredSize(new java.awt.Dimension(40, 20));
        DataPengajar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 270, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("No. HP");
        jLabel7.setPreferredSize(new java.awt.Dimension(40, 20));
        DataPengajar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 270, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nama Lengkap");
        jLabel8.setPreferredSize(new java.awt.Dimension(40, 20));
        DataPengajar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 270, 20));

        buttonGroup1.add(radioButtonLK1);
        radioButtonLK1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioButtonLK1.setForeground(new java.awt.Color(0, 0, 0));
        radioButtonLK1.setText("Laki-Laki");
        radioButtonLK1.setContentAreaFilled(false);
        radioButtonLK1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radioButtonLK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonLK1ActionPerformed(evt);
            }
        });
        DataPengajar.add(radioButtonLK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        buttonGroup1.add(radioButtonPR);
        radioButtonPR.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioButtonPR.setForeground(new java.awt.Color(0, 0, 0));
        radioButtonPR.setText("Perempuan");
        radioButtonPR.setContentAreaFilled(false);
        radioButtonPR.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radioButtonPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonPRActionPerformed(evt);
            }
        });
        DataPengajar.add(radioButtonPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        buttonHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonHapus.setForeground(new java.awt.Color(255, 255, 255));
        buttonHapus.setText("Hapus");
        buttonHapus.setBorder(null);
        buttonHapus.setBorderPainted(false);
        buttonHapus.setContentAreaFilled(false);
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        DataPengajar.add(buttonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 70, 30));

        buttonTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonTambah.setForeground(new java.awt.Color(255, 255, 255));
        buttonTambah.setText("Tambah");
        buttonTambah.setBorder(null);
        buttonTambah.setBorderPainted(false);
        buttonTambah.setContentAreaFilled(false);
        buttonTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        DataPengajar.add(buttonTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 70, 30));

        buttonReset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonReset.setForeground(new java.awt.Color(255, 255, 255));
        buttonReset.setText("Reset");
        buttonReset.setBorder(null);
        buttonReset.setBorderPainted(false);
        buttonReset.setContentAreaFilled(false);
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });
        DataPengajar.add(buttonReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 70, 30));

        buttonUbah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonUbah.setForeground(new java.awt.Color(255, 255, 255));
        buttonUbah.setText("Ubah");
        buttonUbah.setBorder(null);
        buttonUbah.setBorderPainted(false);
        buttonUbah.setContentAreaFilled(false);
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });
        DataPengajar.add(buttonUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 70, 30));

        tblUstadz.setBackground(new java.awt.Color(255, 255, 255));
        tblUstadz.setForeground(new java.awt.Color(0, 0, 0));
        tblUstadz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblUstadz.setGridColor(new java.awt.Color(0, 0, 0));
        tblUstadz.setShowGrid(false);
        tblUstadz.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblUstadzAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblUstadz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUstadzMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUstadz);

        DataPengajar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 530, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Data_Pengajar_Mentahan_1.png"))); // NOI18N
        DataPengajar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 710));

        MainPanelPengurus.add(DataPengajar, "card2");

        add(MainPanelPengurus, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void tidPengajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidPengajarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidPengajarActionPerformed

    private void tnamaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaLengkapActionPerformed

    private void radioButtonPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonPRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonPRActionPerformed

    private void radioButtonLK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonLK1ActionPerformed
        ButtonGroup group = new ButtonGroup();
        group.add(radioButtonLK1);
        group.add(radioButtonPR);
    }//GEN-LAST:event_radioButtonLK1ActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        if(tidPengajar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilih data di tabel yang ingin dihapus");
            return;
        }
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Yakin ingin mengahapus data"
                + "ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (konfirmasi == JOptionPane.YES_OPTION){
            Data_Pengajar pengajar = new Data_Pengajar();
            try {
                pengajar.setId_ustadz((Integer.parseInt(tidPengajar.getText())));
                pengajar.hapusDataUstadz();
                load_table();
                reset();
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "ID pengajar tidak valid.");
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        Data_Pengajar pengajar = new Data_Pengajar();
        pengajar.setNama_ustadz(tnamaLengkap.getText());
        pengajar.setAlamat(talamat.getText());
        pengajar.setNo_hp(tnoHP.getText());
        
        String jenisKelamin = "";
        if (radioButtonLK1.isSelected()){
            jenisKelamin = "Laki-laki";
        } else if (radioButtonPR.isSelected()){
            jenisKelamin = "Perempuan";
        }
        pengajar.setJenis_kelamin(jenisKelamin);
        
        pengajar.tambahDataUstadz();
        load_table();
        reset();
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_buttonResetActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        if (tidPengajar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Pilih data di tabel yang ingin "
                    + "diubah terlebih dahulu.");
            return;
        }
        Data_Pengajar pengajar = new Data_Pengajar();
        try {
            pengajar.setId_ustadz(Integer.parseInt(tidPengajar.getText()));
            
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "ID pengajar tidak valid.");
            return;
        }
        pengajar.setNama_ustadz(tnamaLengkap.getText());
        pengajar.setAlamat(talamat.getText());
        pengajar.setNo_hp(tnoHP.getText());
        
        String jenisKelamin = "";
        if (radioButtonLK1.isSelected()) {
            jenisKelamin = "Laki-laki";
        }else if (radioButtonPR.isSelected()) {
            jenisKelamin = "Perempuan";
        }
        pengajar.setJenis_kelamin(jenisKelamin);
        
        pengajar.ubahDataUstadz();
        load_table();
        reset();
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void tblUstadzAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblUstadzAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblUstadzAncestorAdded

    private void tblUstadzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUstadzMouseClicked
        // TODO add your handling code here:
        int baris = tblUstadz.getSelectedRow();
        if (baris != -1){
            DefaultTableModel model = (DefaultTableModel) tblUstadz.getModel();
            String id = model.getValueAt(baris, 0).toString();
            String nama = model.getValueAt(baris, 1).toString();
            String alamat = model.getValueAt(baris, 2).toString();
            String noHp = model.getValueAt(baris, 3).toString();
            String jenisKelamin = model.getValueAt(baris, 4).toString();
            
            tidPengajar.setText(id);
            tnamaLengkap.setText(nama);
            talamat.setText(alamat);
            tnoHP.setText(noHp);
            
            buttonGroup1.clearSelection();
            if (jenisKelamin.equalsIgnoreCase("Laki-laki")){
                radioButtonLK1.setSelected(true);
            }else if (jenisKelamin.equalsIgnoreCase("Perempuan")) {
                radioButtonPR.setSelected(true);
            }
        }
    }//GEN-LAST:event_tblUstadzMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataPengajar;
    private javax.swing.JPanel MainPanelPengurus;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton radioButtonLK1;
    private javax.swing.JRadioButton radioButtonPR;
    private javax.swing.JTextField talamat;
    private javax.swing.JTable tblUstadz;
    private javax.swing.JTextField tidPengajar;
    private javax.swing.JTextField tnamaLengkap;
    private javax.swing.JTextField tnoHP;
    // End of variables declaration//GEN-END:variables
}
