/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek_kelmp5;

/**
 *
 * @author HP
 */
public class UstadzFrame extends javax.swing.JFrame {

    /**
     * Creates new form UstadzFrame
     */
    public UstadzFrame() {
        initComponents();
    }
    
    void reset() {
        jNamaLengkap1.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        breset = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        jAlamat = new javax.swing.JTextField();
        jNamaLengkap1 = new javax.swing.JTextField();
        jNoHp = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        breset.setBorderPainted(false);
        breset.setContentAreaFilled(false);
        breset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });
        getContentPane().add(breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 80, 30));

        bSimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bSimpan.setEnabled(false);
        getContentPane().add(bSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 80, 30));

        jAlamat.setBackground(new java.awt.Color(255, 255, 255));
        jAlamat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jAlamat.setForeground(new java.awt.Color(0, 0, 0));
        jAlamat.setBorder(null);
        jAlamat.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlamatActionPerformed(evt);
            }
        });
        getContentPane().add(jAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 260, 20));

        jNamaLengkap1.setBackground(new java.awt.Color(255, 255, 255));
        jNamaLengkap1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNamaLengkap1.setForeground(new java.awt.Color(0, 0, 0));
        jNamaLengkap1.setBorder(null);
        jNamaLengkap1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jNamaLengkap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaLengkap1ActionPerformed(evt);
            }
        });
        getContentPane().add(jNamaLengkap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 260, 20));

        jNoHp.setBackground(new java.awt.Color(255, 255, 255));
        jNoHp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jNoHp.setForeground(new java.awt.Color(0, 0, 0));
        jNoHp.setBorder(null);
        jNoHp.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jNoHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoHpActionPerformed(evt);
            }
        });
        getContentPane().add(jNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 260, 20));

        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.setBorder(null);
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek_kelmp5/Data_Pengurus_Mentahan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlamatActionPerformed

    private void jNamaLengkap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaLengkap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaLengkap1ActionPerformed

    private void jNoHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNoHpActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_bresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UstadzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UstadzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UstadzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UstadzFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UstadzFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSimpan;
    private javax.swing.JButton breset;
    private javax.swing.JTextField jAlamat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jNamaLengkap1;
    private javax.swing.JTextField jNoHp;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables

   
}
