 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrame;

/**
 *
 * @author ThinkPad
 */
public class DataSantri extends javax.swing.JFrame {

    /**
     * Creates new form DataSantri
     */
    public DataSantri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        santri_putra = new javax.swing.JLabel();
        santri_putri = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Nama = new javax.swing.JTable();
        Baground = new javax.swing.JLabel();
        Pencarian = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        santri_putra.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        santri_putra.setText("50");
        getContentPane().add(santri_putra, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 80, 90));

        santri_putri.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        santri_putri.setText("50");
        getContentPane().add(santri_putri, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 80, 90));

        Nama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Nama);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 860, 410));

        Baground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Data_Santri_Mentahan.png"))); // NOI18N
        Baground.setText("jLabel1");
        getContentPane().add(Baground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 720));

        Pencarian.setText("jTextField1");
        getContentPane().add(Pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataSantri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Baground;
    private javax.swing.JTable Nama;
    private javax.swing.JTextField Pencarian;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel santri_putra;
    private javax.swing.JLabel santri_putri;
    // End of variables declaration//GEN-END:variables
}
