/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JFrame;
import kelas.classInputsantri;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;


/**
 *
 * @author ThinkPad
 */
public class inputSantri extends javax.swing.JPanel {

    /**
     * Creates new form panelSantri
     */
    public inputSantri() {
        initComponents();
        
    }
    void reset() {
        txtNamleng.setText(null);
        txtTempatlahir.setText(null);
        jTanggalmasuk.setCalendar(null);
        txtAlamat.setText(null);
        buttonGroup1.clearSelection();
        txtWalisantri.setText(null);
        txtNohp.setText(null);
        jTanggalmasuk.setCalendar(null);
        cbStatus.setSelectedItem(null);
    }
    private void jumlahSantri() {
//        try {
//            DataSantri sntr = new DataSantri();
//            
//            // Ambil Putra
//       // ResultSet rsPutra = sntr.jumlahPutra();
//        int putra = 0;
//        //if (rsPutra.next()) {
//            putra = rsPutra.getInt("jumlahPutra");
//        }
//        } catch (Exception e) {
        
      //  }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        dataSantri = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rbPR = new javax.swing.JRadioButton();
        rbLaki = new javax.swing.JRadioButton();
        lblSimpan = new javax.swing.JLabel();
        lblBatal = new javax.swing.JLabel();
        lblReset = new javax.swing.JLabel();
        txtIdsantri = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNohp = new javax.swing.JTextField();
        jTanggalmasuk = new com.toedter.calendar.JDateChooser();
        txtWalisantri = new javax.swing.JTextField();
        txtTempatlahir = new javax.swing.JTextField();
        txtNamleng = new javax.swing.JTextField();
        cbKelas = new javax.swing.JComboBox<>();
        inputSantri = new javax.swing.JPanel();
        jTanggallahir1 = new com.toedter.calendar.JDateChooser();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setOpaque(false);

        dataSantri.setBackground(new java.awt.Color(255, 255, 255));
        dataSantri.setOpaque(false);
        dataSantri.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Jenis Kelamin");
        dataSantri.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 120, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setText("INPUT SANTRI");
        dataSantri.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ID Santri");
        dataSantri.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 80, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tempat Lahir");
        dataSantri.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 120, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Wali Santri");
        dataSantri.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Nama Lengkap");
        dataSantri.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tanggal Lahir");
        dataSantri.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 120, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("No. HP");
        dataSantri.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Tanggal Masuk");
        dataSantri.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 130, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Alamat");
        dataSantri.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 70, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Status Santri");
        dataSantri.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, 110, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Kelas");
        dataSantri.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 50, 30));

        buttonGroup1.add(rbPR);
        rbPR.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rbPR.setText("Perempuan");
        dataSantri.add(rbPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 130, 30));

        buttonGroup1.add(rbLaki);
        rbLaki.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        rbLaki.setText("Laki-Laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });
        dataSantri.add(rbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        lblSimpan.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSimpan.setForeground(new java.awt.Color(255, 255, 255));
        lblSimpan.setText("SIMPAN");
        lblSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSimpanMouseClicked(evt);
            }
        });
        dataSantri.add(lblSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 640, 70, 30));

        lblBatal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBatal.setForeground(new java.awt.Color(255, 255, 255));
        lblBatal.setText("BATAL");
        lblBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBatalMouseClicked(evt);
            }
        });
        dataSantri.add(lblBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 60, 30));

        lblReset.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblReset.setForeground(new java.awt.Color(255, 255, 255));
        lblReset.setText("RESET");
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
        });
        dataSantri.add(lblReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 640, 60, 30));

        txtIdsantri.setBorder(null);
        txtIdsantri.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtIdsantri.setFocusable(false);
        dataSantri.add(txtIdsantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 140, 25));

        txtAlamat.setBorder(null);
        txtAlamat.setOpaque(true);
        dataSantri.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 350, 25));

        txtNohp.setBorder(null);
        txtNohp.setOpaque(true);
        txtNohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNohpActionPerformed(evt);
            }
        });
        dataSantri.add(txtNohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 360, 30));

        jTanggalmasuk.setOpaque(false);
        dataSantri.add(jTanggalmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 370, 40));

        txtWalisantri.setBorder(null);
        txtWalisantri.setOpaque(true);
        dataSantri.add(txtWalisantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 350, 30));

        txtTempatlahir.setBorder(null);
        txtTempatlahir.setOpaque(true);
        dataSantri.add(txtTempatlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 375, 350, 30));

        txtNamleng.setBorder(null);
        txtNamleng.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtNamleng.setOpaque(true);
        dataSantri.add(txtNamleng, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 360, 30));

        dataSantri.add(cbKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 370, 40));

        javax.swing.GroupLayout inputSantriLayout = new javax.swing.GroupLayout(inputSantri);
        inputSantri.setLayout(inputSantriLayout);
        inputSantriLayout.setHorizontalGroup(
            inputSantriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        inputSantriLayout.setVerticalGroup(
            inputSantriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        dataSantri.add(inputSantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTanggallahir1.setOpaque(false);
        dataSantri.add(jTanggallahir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 370, 40));

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mukim", "Tidak Mukim" }));
        dataSantri.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 370, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Data_Input_Santri.png"))); // NOI18N
        dataSantri.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataSantri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dataSantri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        add(mainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void lblBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBatalMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblBatalMouseClicked

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblResetMouseClicked

    private void lblSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSimpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSimpanMouseClicked

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void txtNohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNohpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbKelas;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JPanel dataSantri;
    private javax.swing.JPanel inputSantri;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser jTanggallahir1;
    private com.toedter.calendar.JDateChooser jTanggalmasuk;
    private javax.swing.JLabel lblBatal;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblSimpan;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPR;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtIdsantri;
    private javax.swing.JTextField txtNamleng;
    private javax.swing.JTextField txtNohp;
    private javax.swing.JTextField txtTempatlahir;
    private javax.swing.JTextField txtWalisantri;
    // End of variables declaration//GEN-END:variables
}
